name: esnatch
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"
# packages
dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #utility packages

  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  connectivity_plus: ^5.0.1

  #product specific
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  #firebase packages
  firebase_core: ^2.23.0
  # firebase_storage: ^12.0.1
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #local asets
  assets:
    - assets/images/on_boarding_images/
    - assets/fonts/
    - assets/icons/categories/
    - assets/icons/payment_methods/

    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/reviews/
    - assets/images/products/
  # local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
